---
- name: Cleanup disk space
  hosts: all
  become: yes
  tasks:
    - name: Disk Cleanup
      ansible.builtin.debug:
        msg: "{{ ansible_eda.event }}"
     ##keep it for ref as command can be changed
     #ansible.builtin.shell: "find /var/log -type f -name "*.log" -mtime +3" #-delete"
    - name: Take backup before cleanup
      ansible.builtin.shell: "tar -czvf latest-backup.tar.gz code*.py"
      args:
        chdir: /home/nrathi
       
    - name: copy to secure location
      ansible.builtin.shell: "cp -ar latest-backup.tar.gz /backup/latest-backup.tar.gz"
      args:
        chdir: /home/nrathi

    - name: find files to be deleted on {{ ansible_eda.event.alert.labels.mountpoint }}
      ansible.builtin.shell: "find {{ ansible_eda.event.alert.labels.mountpoint }} -type f  -name *.log -mtime +{{ cleanup }}"
      register: fileslist

    - name: display list
      ansible.builtin.debug:
        msg: "{{ fileslist.stdout }}"

    - name: delete file using shell utility on {{ ansible_eda.event.alert.labels.mountpoint }}
      ansible.builtin.shell: "find {{ ansible_eda.event.alert.labels.mountpoint }} -type f -name *.log  -mtime +{{ cleanup }} -delete" 


    - name: Checking Disk Status after the Cleanup
      ansible.builtin.shell: "df -h"
      register: dick_stat

    - ansible.builtin.debug:
        msg: "{{ dick_stat.stdout_lines }}"               
    #- name: Clean /tmp
    #  shell: find /tmp -type f -mtime +1 -delete


