---
- name: Cleanup disk space
  hosts: all
  become: yes
  tasks:
    - name: Disk Cleanup
      ansible.builtin.debug:
        msg: "{{ ansible_eda.event }}"
     ##keep it for ref as command can be changed
     #ansible.builtin.shell: "find /var/log -type f -name "*.log" -mtime +3" #-delete"
    - name: find files to be deleted on {{ ansible_eda.event.alert.labels.mountpoint }}
      ansible.builtin.shell: "find {{ ansible_eda.event.alert.labels.mountpoint }} -type f -mtime +{{ cleanup }}"
      register: fileslist

    - name: display list
      ansible.builtin.debug:
        msg: "{{ fileslist.stdout }}"

    - name: delete file using shell utility on {{ ansible_eda.event.alert.labels.mountpoint }}
      ansible.builtin.shell: "find {{ ansible_eda.event.alert.labels.mountpoint }} -type f -mtime +{{ cleanup }} -delete" 


    - name: Checking Disk Status after the Cleanup
      ansible.builtin.shell: "df -h"
      register: disk_stat

    - ansible.builtin.debug:
        msg: "{{ disk_stat.stdout_lines }}"               
    #- name: Clean /tmp
    #  shell: find /tmp -type f -mtime +1 -delete

    - name: settting up the counter
      ansible.builtin.set_stats:
        data:
          counter: 1
      when: "{{ cleanup }} == 6"  
###############
    - name: settting up the counter
      ansible.builtin.set_stats:
        data:
          counter: 2
      when: "{{ cleanup }} == 3"  
#########
    - name: settting up the counter
      ansible.builtin.set_stats:
        data:
          counter: 3
      when: "{{ cleanup }} == 1"        
