---
- name: Collect OS and package data for compliance
  hosts: all
  gather_facts: yes
  become: true

  tasks:
    - name: Get OS release info
      shell: cat /etc/os-release
      register: os_release
      changed_when: false

    - name: Get kernel version
      command: uname -r
      register: kernel_version
      changed_when: false

    - name: List all installed packages
      package_facts:
        manager: auto


    - name: display
      ansible.builtin.debug:
        msg: >
              Package: {{ item.1.name }}
              Version: {{ item.1.version }}
              Release: {{ item.1.release }}
              Arch: {{ item.1.arch }}
      loop: "{{ ansible_facts.packages | dict2items | subelements('value') }}"
      loop_control:
        label: "{{ item.1.name }}-{{ item.1.version }}"


    - name: Genrate Email content to Send in Email
      ansible.builtin.template:
        src: packages_email_alert_html.j2
        dest: /tmp/alert_email.html
      when: email

    - name: Send email Alert
      community.general.mail:
        host: smtp.gmail.com
        port: 587
        subtype: html
        to:
        - "nrathi@redhat.com"
        subject: "Alert: Password Password Expires in next 7 days"
        body: "{{ lookup('file', '/tmp/alert_email.html') }}"
        username: "dmeonavneet@gmail.com"
        password: "rbfqhoincpyouxqk"
      changed_when: True
      when: email      