---
- name: Disk space filling play
  hosts: all
  become: yes
  tasks:
    - name: script function
      ansible.builtin.debug:
        msg: "its a simple script which will fill the space with dummy data"
        
    - name: genrate the dummy files in /home directory
      ansible.builtin.shell: "sh /home/nrathi/random.sh"
      register: fileslist

    - name: Display genrated load
      ansible.builtin.shell: df -h
      register: disk_status

    - name: disk_status
      ansible.builtin.debug:
        msg: "{{ disk_status }}"

    - name: Make sure service is up and running | Nginx service
      ansible.builtin.service:
        name: nginx
        state: stopped
      become: true
      register: nginx_stop
    
    - name: make sure service is stopped
      ansible.builtin.debug:
        msg: "{{ nginx_stop }}"

    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      ansible.posix.selinux:
        policy: targeted
        state: permissive
      register: se_permessive

    - name: display se_status
      ansible.builtin.debug:
        msg: "{{ se_permessive }}"

    - name: make sure SE is permissive
      ansible.builtin.shell: cat /etc/selinux/config
      register : readfile 

    - name: display file
      ansible.builtin.debug:
        msg: "{{ readfile }}"   

    - name: make sure SE is permissive
      ansible.builtin.shell: getenforce
      register : readgetenforce 

    - name: display file
      ansible.builtin.debug:
        msg: "{{ readgetenforce }}"      