---
- name: its a simple ansible script which will create issues like diskspace,stop service and complaince
  hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: check Disk status before
      ansible.builtin.shell: df -h
      register: disk_status_before

    - name: disk_status of Disk load before
      ansible.builtin.debug:
        msg: "{{ disk_status_before }}"

    - name: genrate the dummy files in /home directory
      ansible.builtin.shell: "sh /opt/random.sh"
      register: fileslist

    - name: check Disk status After load
      ansible.builtin.shell: df -h
      register: disk_status

    - name: disk_status of Disk load after the load is put
      ansible.builtin.debug:
        msg: "{{ disk_status }}"

    - name: Make sure service is Stopped| Nginx service
      ansible.builtin.service:
        name: nginx
        state: stopped
      become: true
      register: nginx_stop
    
    - name: Show the status of Nginx service
      ansible.builtin.debug:
        msg: "{{ nginx_stop }}"

    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      ansible.posix.selinux:
        policy: targeted
        state: permissive
      register: se_permessive

    - name: display se_status
      ansible.builtin.debug:
        msg: "{{ se_permessive }}"

    - name: make sure SE is permissive
      ansible.builtin.shell: cat /etc/selinux/config
      register : readfile 

    - name: display the content of /etc/selinux/config
      ansible.builtin.debug:
        msg: "{{ readfile }}"   

    - name: make sure SE is permissive
      ansible.builtin.shell: getenforce
      register : readgetenforce 

    - name: display status getenforce
      ansible.builtin.debug:
        msg: "{{ readgetenforce }}"      