# restart_nginx.yml
---
- name: Restarting the Nginx if port 80 is down
  hosts: all
  gather_facts: false
  force_handlers: true
  ignore_unreachable: true 
  tasks:
    - name: Try to ping the host
      block:
        - name: Ping the host
          ansible.builtin.ping:

        - name: Ping is success
          ansible.builtin.debug:
            msg: "{{inventory_hostname}} is reachanble from Ansible Controller...!"            
      rescue:
          - name: Genrate Email content to Send in Email | Server is unreachable
            ansible.builtin.template:
              src: email_alert.html.j2
              dest: /tmp/alert_email.html
            run_once: true  
            delegate_to: 127.0.0.1
            when: nginx_restart.changed != 'true'

          - name: Email Alert if fail server is unreachable
            when: nginx_restart.changed != 'true'
            mail:
              host: smtp.gmail.com
              port: 587
              subtype: html
              to:
              - "nrathi@redhat.com"
              subject: "Alert: Host not reachable on SSH {{ inventory_hostname }}"
              body: "{{ lookup('file', '/tmp/alert_email.html') }}"
              username: "dmeonavneet@gmail.com"
              password: "rbfqhoincpyouxqk"
            run_once: true  
            delegate_to: 127.0.0.1
            changed_when: True   

    - name: Firewalld |Open port 80 using firewalld
      #ignore_errors: true
      #ignore_unreachable: true
      ansible.posix.firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
      notify: Reload firewalld to apply changes

    - name: Make sure service is up and running | Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
      become: true
      register: nginx_restart
      #ignore_errors: true
      #ignore_unreachable: true

    - ansible.builtin.debug:
        msg: "{{ nginx_restart }}"
 
  handlers:
    - name: Reload firewalld | To apply changes
      ansible.builtin.service:
        name: firewalld
        state: reloaded