---
- name: Check user password expiry and alert if expiring within 7 days
  hosts: all
  become: true
  gather_facts: yes

  vars:
    expiry_threshold_days: 7
    excluded_users:
      - root
      - shutdown
      - halt
      - sync
      - nobody

  tasks:

    - name: Get list of normal users (UID ≥ 1000)
      shell: "awk -F: '$3 >= 1000 {print $1}' /etc/passwd"
      register: user_list_raw
      changed_when: false

    - name: Filter out excluded users
      set_fact:
        user_list: "{{ user_list_raw.stdout_lines | difference(excluded_users) }}"

    - name: Get expiry date for each user
      shell: chage -l {{ item }} | grep 'Password expires'
      register: chage_results
      loop: "{{ user_list }}"
      changed_when: false

    - name: Check if password expires within threshold
      vars:
        expiry_date: "{{ item.stdout.split(': ')[1] }}"
      debug:
        msg: "⚠️ Password for user {{ item.item }} expires on {{ expiry_date }}"
      when: >
        expiry_date != "never" and
        ( ( ( lookup('pipe', 'date -d \"' + expiry_date + '\" +%s') | int ) -
            ( ansible_date_time.epoch | int ) ) / 86400 ) <= expiry_threshold_days
      loop: "{{ chage_results.results }}"