---
- name: Check user password expiry and alert if expiring within 7 days
  hosts: all
  become: true
  gather_facts: yes

  vars:
    expiry_threshold_days: 7
    excluded_users:
      - root
      - shutdown
      - halt
      - sync
      - nobody

  tasks:

    - name: Get list of normal users (UID ≥ 1000)
      shell: "awk -F: '$3 >= 1000 {print $1}' /etc/passwd"
      register: user_list_raw
      changed_when: false

    - name: Filter out excluded users
      set_fact:
        user_list: "{{ user_list_raw.stdout_lines | difference(excluded_users) }}"

    - name: Get expiry date for each user
      shell: chage -l {{ item }} | grep 'Password expires'
      register: chage_results
      loop: "{{ user_list }}"
      changed_when: false

    - name: Check if password expires within threshold
      vars:
        expiry_date: "{{ item.stdout.split(': ')[1] }}"
      debug:
        msg: "⚠️ Password for user {{ item.item }} expires on {{ expiry_date }}"
      when: >
        expiry_date != "never" and
        ( ( ( lookup('pipe', 'date -d \"' + expiry_date + '\" +%s') | int ) -
            ( ansible_date_time.epoch | int ) ) / 86400 ) <= expiry_threshold_days
      loop: "{{ chage_results.results }}"
      loop_control:
         label: "{{ item.item }}"

    - name: Create a directory /tmp/pass if it does not exist
      ansible.builtin.file:
        path: /tmp/pass
        state: directory
        mode: '0755'

    - name: Remove old  data files
      ansible.builtin.file:
        path: /tmp/pass/password.csv
        state: absent    

    - name: put details in file
      vars:
        expiry_date: "{{ item.stdout.split(': ')[1] }}"
      ansible.builtin.shell: "echo {{inventory_hostname}},{{ item.item }},{{expiry_date}} >> /tmp/pass/password.csv"
      when: >
        expiry_date != "never" and
        ( ( ( lookup('pipe', 'date -d \"' + expiry_date + '\" +%s') | int ) -
            ( ansible_date_time.epoch | int ) ) / 86400 ) <= expiry_threshold_days
      loop: "{{ chage_results.results }}"
      loop_control:
         label: "{{ item.item }}"

    - name: Copy file on Control Pod
      ansible.builtin.fetch:
        src: /tmp/pass/password.csv
        dest: "/tmp/pass/password_{{inventory_hostname}}.csv"
        flat: yes
        
- hosts: localhost
  connection: local
  vars:
    email: false
  tasks:
    - name: Remove old  data files
      ansible.builtin.file:
        path: /tmp/pass.txt
        state: absent    

    - name: Assemble from fragments from a directory
      ansible.builtin.assemble:
        src: /tmp/pass
        dest: /tmp/pass.txt

    - name: Read users from CSV file and return a list
      community.general.read_csv:
        path: /tmp/pass.txt
        fieldnames: host,username,password,year
        delimiter: ','
      register: passdata

    - name: read the content of password expiry
      ansible.builtin.debug:
        msg: "{{ passdata.list }}"
      when: email is false

    - name: Genrate Email content to Send in Email
      ansible.builtin.template:
        src: password_email_alert_html.j2
        dest: /tmp/alert_email.html
      when: email

    - name: Send email Alert
      community.general.mail:
        host: smtp.gmail.com
        port: 587
        subtype: html
        to:
        - "nrathi@redhat.com"
        subject: "Alert: Password Password Expires in next 7 days"
        body: "{{ lookup('file', '/tmp/alert_email.html') }}"
        username: "dmeonavneet@gmail.com"
        password: "rbfqhoincpyouxqk"
      changed_when: True
      when: email        