---
- name: Check user password expiry and alert if within 7 days
  hosts: all
  become: true
  gather_facts: false

  vars:
    expiry_threshold_days: 7
    excluded_users:
      - root
      - shutdown
      - halt
      - sync
      - nobody

  tasks:

    - name: Get list of all normal users (UID ≥ 1000)
      ansible.builtin.shell: "awk -F: '$3 >= 1000 {print $1}' /etc/passwd"
      register: user_list_raw
      changed_when: false

    - name: Set filtered user list
      set_fact:
        user_list: "{{ user_list_raw.stdout_lines | difference(excluded_users) }}"

    - name: Get password expiry info for each user
      ansible.builtin.shell: chage -l {{ item }}
      loop: "{{ user_list }}"
      register: chage_info
      changed_when: false

    # - name: Parse expiry dates
    #   set_fact:
    #     expiring_users: >-
    #       {{
    #         chage_info.results
    #         | selectattr('stdout', 'search', 'Password expires')
    #         | selectattr('stdout', 'search', '(?<!never)')
    #         | map(attribute='stdout_lines')
    #         | map('select', 'search', 'Password expires')
    #         | map('join')
    #         | zip(user_list)
    #         | map('reverse')
    #         | map('list')
    #         | map('combine', [{'user': '', 'expiry': ''}])
    #         | selectattr('expiry', 'defined')
    #         | selectattr('expiry', 'search', '[a-zA-Z]')
    #         | map(attribute='user')
    #       }}

    # - ansible.builtin.debug:
    #     msg: "{{ expiring_users }}"      

    - name: Show expiring users (basic alert)
      ansible.builtin.debug:
        msg: "User {{ item }} has a password expiring within the next {{ expiry_threshold_days }} days."
      loop: "{{ user_list }}"
      when: >
        (
          lookup('pipe', "date -d \"" + (chage_info.results[loop.index0].stdout_lines | select('search', 'Password expires') | list | first | regex_replace('Password expires\\s*:\\s*', '') | trim) + "\" +%s")
          | int
          -
          ansible_date_time.epoch | int
        ) / 86400 <= expiry_threshold_days