---
- name: 
  hosts: all
  gather_facts: true
  vars_files: vars/command.yml
  tasks:
    - name: we will be using module
      loop: "{{lookup('ansible.builtin.dict',command, wantlist=True)}}"
      ansible.builtin.shell: "{{ item['value']['command'] }}"
      args:
        "{{ item['value']['args'] }}"  
      delegate_to : "{{ item['value']['dalegate_to']| default(omit) }}"
