---
- name: 
  hosts: all
  gather_facts: true
  vars_files: vars/command.yml
  
  tasks:
    - name: Include a tasks for dates
      ansible.builtin.include_tasks: date.yml

    - name: we will be using module
      loop: "{{lookup('ansible.builtin.dict',command, wantlist=True)}}"
      ansible.builtin.shell: "{{ item['value']['pipe'] | default(\" \") }} {{ item['value']['command'] }}"
      args: 
        "{{ item['value']['args'] }}"  
      delegate_to : "{{ item['value']['dalegate_to']| default(omit) }}"
      register: my_commands
    

    - name: Display the output of commands
      ansible.builtin.debug:
        msg: "{{ my_commands }}" 