## list of mandetory params
# 1. command
# 2. args  
command:
  com1:
   # module_name: ansible.builtin.shell
    command: "date"
    dalegate_to: localhost
    args: 
      chdir: "/root/"
      creates: "/root/somthing.txt"

  com2:
   # module_name: ansible.builtin.shell
    command: "date"
    args: 
      chdir: "/root/"
      creates: "/root/somthing.txt"   

  com3:
   # module_name: ansible.builtin.shell
    command: "echo \"This is for testing\" && mkdir navneet_{{ selected_date_fullm }}"  
    args: 
      chdir: "/root/"
      creates: "/root/somthing.txt"     
    dalegate_to: localhost

  com4:
   # module_name: ansible.builtin.shell
    command: "echo \"This is for testing\" {{ selected_date }} && mkdir -p demo{{ selected_date }} "  
    args: 
      chdir: "/root/"
      creates: "/root/somthing.txt"     
    #dalegate_to: localhost

  com5:
   # module_name: ansible.builtin.shell
    command: "echo \"This is for Error testing\" {{ selected_date }} && mkdir -p rahul_{{ selected_date }}"  
    args: 
      chdir: "/root/"
      creates: "/root/somthing.txt"     
    #dalegate_to: localhost     

  com6:
   # module_name: ansible.builtin.shell
    command: "echo \"This is for testing\" {{ selected_date }} && mkdir -p rahul_{{ selected_date }} "  
    args: 
      chdir: "/root/"
      creates: "/root/somthing.txt"     
    #dalegate_to: localhost        
  # com2:  
  #   name: app3
  #   version: v2
  #   port: 8083
  #   host: podman1
  # com3:
  #   name: app5
  #   version: v4
  #   port: 8085
  #   host: podman1
  # com4:
  #   name: app7  
  #   version: v2
  #   port: 8087
  #   host: podman1
  # com5:
  #   name: app11
  #   version: v3
  #   port: 8091
  #   host: podman1