---
- name: Basic Check webserver
  hosts: all
  sources:
    - ansible.eda.url_check:
        urls:
          - http://192.168.64.40
        delay: 45
    - ansible.eda.alertmanager:
            host: 0.0.0.0
            port: 5050
            data_alerts_path: alerts
            data_host_path: labels.instance
            data_path_separator: .
            skip_original_data: true 
  rules:
    - name: SELinux is disabled
      condition:
        all: 
          - event.alert.labels.alertname == "selinux disabled" 
          - event.alert.status == "firing"
      action:
        run_job_template:
          name: Apply baseline
          organization: Default
          job_args:
            limit: "{{ event.meta.hosts }}"

    - name: SELinux was enabled and now its fixed
      condition:
        all:
          - event.alert.labels.alertname == "selinux disabled" 
          - event.alert.status == "resolved"
      action:
        debug:
          msg: "enabled on: {{ event.meta.hosts }}"

    - name: DiskSpaceLow -r1
      condition: 
        all:
          - event.alert.labels.alertname == "DiskSpaceLow" 
          - event.alert.status == "firing"
          - eventcount | default("0") | int == 0
      action:
        run_job_template:
          name: Apply_disk_cleanup
          organization: Default
          job_args:
            limit: "{{ event.meta.hosts }}"
        post_events:
          - set_fact:
              eventcount = 1         

    - name: DiskSpaceLow -r2
      condition: 
        all:
          - event.alert.labels.alertname == "DiskSpaceLow" 
          - event.alert.status == "firing"
          - eventcount | int == 1
      action:
        run_job_template:
          name: Apply_disk_cleanup
          organization: Default
          job_args:
            limit: "{{ event.meta.hosts }}"
        post_events:
          - set_fact:
              eventcount = 2           

    - name: DiskSpaceLow -r3
      condition: 
        all:
          - event.alert.labels.alertname == "DiskSpaceLow" 
          - event.alert.status == "firing"
          - eventcount | int == 2
      action:
        run_job_template:
          name: Apply_disk_cleanup
          organization: Default
          job_args:
            limit: "{{ event.meta.hosts }}"
        post_events:
          - set_fact:
              eventcount | int = 3            

    - name: DiskSpaceLow issue and now its fixed
      condition: 
        all:
          - event.alert.labels.alertname == "DiskSpaceLow" 
          - event.alert.status == "resolved"
      action:
        debug:
          msg: "enabled on: {{ event.meta.hosts }}"
        post_events:
          - set_fact:
              eventcount | int = 0             

    - name: USB device detected
      condition:
        all: 
          - event.alert.labels.alertname == "USB Device Detected" 
          - event.alert.status == "firing"
      action:
        run_job_template:
          name: 01-js-usb
          organization: Default
          job_args:
            limit: "{{ event.meta.hosts }}"
          extra_vars:  
            usb_disable: true

    - name: UserPasswordExpired except Administrato
      condition: 
        all:
          - event.alert.labels.alertname == "UserPasswordExpired except Administrator" 
          - event.alert.status == "firing"
      action:
        run_job_template:
          name: 01-email-alert
          organization: Default
          job_args:
            limit: "{{ event.meta.hosts }}"

    - name: Restart Nginx
      condition: event.url_check.status == "down"
      throttle:
        once_after: 1 minutes
      action:
        run_job_template:
          name: nginx_restart
          organization: Default

   # - name: Nginx up
   #   condition: event.url_check.status != "down"
   #   action:      
   #     debug:
   #       msg: "Nginx is up and runing..!"

    - name: Capture all other events from this source
      condition: event.alert is defined
      action:
        debug: