---
- name: Basic Check webserver
  hosts: all
  sources:
    - ansible.eda.url_check:
        urls:
          - http://192.168.1.23
        delay: 30
  rules:
    - name: Restart Nginx
      condition: event.url_check.status == "down"
      action:
        run_job_template:
          name: nginx_restart
          organization: Default
#          job_args:
#            limit: "{{ event.meta.hosts }}"