---
- name: Basic Check webserver
  hosts: all
  sources:
    - ansible.eda.url_check:
        urls:
          - http://192.168.64.40
        delay: 45
    - ansible.eda.alertmanager:
            host: 0.0.0.0
            port: 5050
            data_alerts_path: alerts
            data_host_path: labels.instance
            data_path_separator: .
            skip_original_data: true 
  rules:
    - name: Initialize facts
      condition: event.alert.labels.alertname == "DiskSpaceLow" and event.alert.status == "firing" 
      action:
        set_fact:
           fact:
             cleanup: 0
          
    - name: DiskSpaceLow -r1
      condition: event.alert.labels.alertname == "DiskSpaceLow" and event.alert.status == "firing" and  facts.cleanup == 0
      action:
        run_job_template:
          name: Apply_disk_cleanup
          organization: Default
          job_args:
            limit: "{{ event.meta.hosts }}"
            extra_vars:
              cleanup: 6
          set_fact:    
          #  ruleset: DiskSpaceLow -r2
            fact:
              cleanup : 6        

    - name: DiskSpaceLow -r2
      condition:  event.alert.labels.alertname == "DiskSpaceLow" and event.alert.status == "firing" and  facts.cleanup == 6
      action:
        run_job_template:
          name: Apply_disk_cleanup
          organization: Default
          job_args:
            limit: "{{ event.meta.hosts }}"
            extra_vars:
              cleanup: 3
          set_fact:    
           # ruleset: DiskSpaceLow -r3
            fact:
              cleanup : 3                

    - name: DiskSpaceLow -r3
      condition: event.alert.labels.alertname == "DiskSpaceLow" and event.alert.status == "firing" and facts.cleanup == 3
      action:
        run_job_template:
          name: Apply_disk_cleanup
          organization: Default
          job_args:
            limit: "{{ event.meta.hosts }}"
            extra_vars:
              cleanup: 1
          set_fact:    
            ruleset: DiskSpaceLow issue and now its fixed  
            fact:
              cleanup : 1                

    - name: DiskSpaceLow issue and now its fixed
      condition: event.alert.labels.alertname == "DiskSpaceLow" and event.alert.status == "resolved"
      action:
        debug:
          msg: "enabled on: {{ event.meta.hosts }}"
        fact:
          cleanup = 0   
   
    - name: Capture all other events from this source
      condition: event.alert is defined
      action:
        debug: